### ISSUE TITLE
BBOX parser not conforming to specs

### ISSUE THREAD

**Issue by StefanBrand** [geopython/pycql#1]
The parser for BBOX demands a CRS, while in the [ECQL specification](https://docs.geoserver.org/latest/en/user/filter/ecql_reference.html#spatial-predicate) this is optional:

`BBOX ( Expression , Number , Number , Number , Number [ , CRS ] )`

E.g. this works: `BBOX(geometry,13,48,14,49,"EPSG:4326")`
while this throws an error: `BBOX(geometry,13,48,14,49)` although it is valid according to specs.

Error: `Syntax error at token RPAREN ) 25 1`

`pycql` should not demand a CRS.

**Comment by constantinius** [comment]
This is fixed with f6025d6c92f2ef18d55d2c2af60b8ba0786e72d2
