### ISSUE TITLE
Transition to `pygeofilters`

### ISSUE THREAD

**Issue by constantinius** [geopython/pycql#11]
`pycql` originally only supports the old CSW CQL dialect. But more filter languages/dialects exist:

- OGC filter encoding specification (FES) or OGC filters: http://docs.opengeospatial.org/is/09-026r2/09-026r2.html
- OGC API features/records CQL text definition and JSON encoding: http://docs.ogc.org/DRAFTS/19-079.html

As all these filter languages offer more or less the same functionality, it is envisioned to 

- Create a new python package (in favor of renaming this package): `pygeofilters` where most of the pycql source code will be copied to
- Update the AST to accommodate the features of all languages/dialects (potentially with type-checks via [pydantic](https://pydantic-docs.helpmanual.io/))
- Implement the parsers for each language encoding/dialect

When this is done, this git repository shall be archived and redirect to `pygeofilters`

**Comment by tomkralidis** [comment]
Makes sense. Should we call it `pygeofilter` or `pygeofilters` ? My vote would be for `pygeofilter`.

**Comment by constantinius** [comment]
New repo is up: https://github.com/geopython/pygeofilter

**Comment by bitner** [comment]
@tomkralidis @constantinius if pygeofilter is completely replacing pycql development, we should add something to the top of the README pointing folks over to pygeofilter

**Comment by constantinius** [comment]
Yes, you are right, will do so!

**Comment by constantinius** [comment]
Done with b41a395
